db:
  username: "postgres"
  password: "qwerty"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

server:
  port: "8080"
  host: "localhost"
  env: "local"
  timeout: "10h"

redis:
  host: "localhost"
  port: "6379"