services:

  kafka:
    container_name: kafka-0
    hostname: kafka
    image: apache/kafka:latest
    ports:
      - 9092:9092
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:  
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      # KAFKA_CREATE_TOPICS: "example:2:1"
      
  zookeeper:
    # conteiner_name: zookeeper
    image: zookeeper
    ports:
      - 2181:2181

  user-service:
    container_name: user-service
    image: user-service
    build:
      context: ./services/user
      dockerfile: local.Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./services/user:/usr/src/app
    depends_on:
      - user-postgres
      - kafka

  user-postgres:
    container_name: user-postgres
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      PGSSLMODE: "disable"
    volumes:
      - ./services/user/migration/000001_init.up.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
