services:

  zookeeper:
    # conteiner_name: zookeeper
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEPER_SERVER_ID: 1
      ZOOKEEPER_INIT_ID: 3
      ZOOKEEPER_SYNC_LIMIT: 2
  
  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: confluentinc/cp-kafka:latest
    ports:
      - 9091:9091
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:  
      KAFKA_ADVERTISED_HOST_NAME: "kafka1"
      # KAFKA_ADVERTISED_PORT: "9091"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29091,PLAINTEXT_HOST://localhost:9091

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9020:8080
    depends_on:
      - kafka1
    environment: 
      AUTH_TYPE: DISABLED
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29091
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  user-service:
    container_name: user-service
    image: user-service
    build:
      context: ./services/user
      dockerfile: local.Dockerfile
    environment:
      - DB_HOST=user-postgres
      - KAFKA_ADDRS=kafka1:9091
    ports:
      - "8080:8080"
    volumes:
      - ./services/user:/usr/src/app
    depends_on:
      - user-postgres
      - kafka1

  user-postgres:
    container_name: user-postgres
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      PGSSLMODE: "disable"
    volumes:
      - ./services/user/migration/000001_init.up.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
